
module.exports = [
	'./src/vendor/jquery.js',
	'./src/Engine/Assets.js',
	'./src/Engine/EventEmitter/EventEmitter.js',
	'./src/Engine/Utils.js',
	'./src/Engine/Api.js',
	'./src/Engine/GameLoad.js',
	'./src/Engine/Core.js',
	'./src/Engine/Sound.js',
	'./src/Engine/Mouse.js',
	'./src/Engine/GameComponents.js',
	'./src/Engine/Loader.js',
	'./src/Engine/Queue.js',
	'./src/Engine/Animations.js',
	'./src/Engine/Actions.js',
	'./src/Engine/Turns.js',
	'./src/Engine/Sprites.js',
	'./src/Engine/Chat/ChatBox.js',
	'./src/Engine/Chat/Constants.js',
	'./src/Engine/Init.js',
	'./src/Engine/EndGame.js',
	'./src/Engine/Effects.js',
	'./src/Engine/CardEffects.js'
];
