global.C = {
	QUEUE_PROCESS_INTERVAL: 1000,
	GAME_CLEAR_FINISHED_INTERVAL: 5000,
	
	// Player status
	PLAYER_TYPE: 'PLAYER',
	PLAYER_IDLE:'PLAYER_IDLE',
	PLAYER_IN_GAME:'PLAYER_INGAME',
	PLAYER_POST_GAME:'PLAYER_POST_GAME',
	PLAYER_IN_QUEUE:'PLAYER_IN_QUEUE',
	PLAYER_CREATING_GAME:'PLAYER_CREATING_GAME',

	// Game status
	GAME_TYPE: 'GAME_TYPE',
	GAME_IDLE: 'GAME_IDLE',
	GAME_STARTING: 'GAME_STARTING',
	GAME_ACTIVE: 'GAME_ACTIVE',
	GAME_END: 'GAME_ENDED',

	GAME_END_TYPE_SURRENDER: 'SURRENDER',
	GAME_END_TYPE_NORMAL: 'NORMAL',
	GAME_END_DISCONNECT: 'DISCONNECT',

	GAME_VICTORY: 'VICTORY',
	GAME_DEFEAT: 'DEFEAT',

	// Game turns
	TURN_TYPE_MULLIGAN: 'MULLIGAN',
	TURN_TYPE_TURN: 'TURN',
	TURN_TYPE_DEFENSE: 'DEFENSE',
	
	TURN_TYPE_MULLIGAN_INTERVAL: 5 * 1000,
	TURN_TYPE_TURN_INTERVAL: 5 * 1000,
	TURN_TYPE_DEFENSE_INTERVAL: 5 * 1000
};